version: '3.4'

services:
  redis:
    container_name: redis

    image: redis
    ports:
      - 6379:6379
  back:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: back

    ports:
      - 8080:8080
    depends_on:
      - redis